# Generated by Django 5.1.5 on 2025-02-10 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_booking_price_booking_show_time_booking_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='show_time',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
