# Generated by Django 5.1.5 on 2025-02-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_booking_date_booking_created_at'),
    ]

    operations = [
    ]
