# Generated by Django 5.1.5 on 2025-02-16 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0015_seatreservation_price_seatreservation_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seat",
            name="theater",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.theater"
            ),
        ),
    ]
