# Generated by Django 5.1.5 on 2025-02-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_actor_remove_movie_cast_movie_is_recommended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('Action', 'Action'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('Animation', 'Animation'), ('Documentary', 'Documentary')], default='Action', max_length=20),
        ),
    ]
