# Generated by Django 5.1.5 on 2025-02-19 17:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_theater_show_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='show_time',
        ),
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='theater',
            name='show_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
