# Generated by Django 4.2.7 on 2025-02-22 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0027_alter_movie_cast_alter_seat_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='showtime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
