# Generated by Django 5.1.5 on 2025-02-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_theater_total_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='total_seats',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
