# Generated by Django 5.1.5 on 2025-02-15 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0014_booking_is_paid_booking_total_price_movie_genre_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatreservation",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="seatreservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Expired", "Expired"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
