# Generated by Django 5.1.5 on 2025-02-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_remove_theater_show_time_remove_theater_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theater',
            name='show_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
