# Generated by Django 4.2.7 on 2025-02-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0025_remove_movie_show_time_seat_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(default='Bolleywood'),
        ),
    ]
