# Generated by Django 4.2.7 on 2025-02-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_movie_cast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.TextField(default='Bollywood'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
